/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Blogs;

import com.mongodb.client.MongoCollection;
import java.awt.Image;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

import com.mongodb.client.MongoDatabase;
import database.CRUDOperations;
import database.Connection;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Business.Business;
import model.Personnel.Doctor;
import org.bson.Document;
import org.bson.types.ObjectId;


public class BlogUploadJPanel extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    Business business;
//    Blog blog;
    MongoDatabase database;
    CRUDOperations crud = new CRUDOperations();
    MongoCollection<Document> blogCollection;
    ObjectId doctorId;

    /**
     * Creates new form blogUploadJPanel
     */
    private final JFileChooser fileChooser = new JFileChooser();
    ImageIcon logoImage;

    public BlogUploadJPanel(JPanel cardSequencePanel, MongoDatabase database, Business business, ObjectId doctorId) {
        initComponents();
        this.CardSequencePanel = cardSequencePanel;
        this.database = new Connection().connectToDatabase();
        this.business = business;
        this.doctorId = doctorId;
        this.blogCollection = this.database.getCollection("Blog");

        FileFilter jpegFilter = new FileNameExtensionFilter("JPEG file", "jpg", "jpeg");
        FileFilter pngFilter = new FileNameExtensionFilter("PNG file", "png", "png");

        fileChooser.addChoosableFileFilter(jpegFilter);
        fileChooser.addChoosableFileFilter(pngFilter);
        fileChooser.setFileFilter(pngFilter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBlogPostHeader = new javax.swing.JLabel();
        lblBlogAddDate = new javax.swing.JLabel();
        txtBlogPostDate = new javax.swing.JTextField();
        lblBlogPostTitle = new javax.swing.JLabel();
        txtBlogPostTitle = new javax.swing.JTextField();
        lblBlogPostField = new javax.swing.JLabel();
        txtBlogPostField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaBlogPostDescription = new javax.swing.JTextArea();
        lblBlogPostDescrp = new javax.swing.JLabel();
        btnBlogPublish = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblBlogPostHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBlogPostHeader.setText("WELCOME TO BLOG!");

        lblBlogAddDate.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblBlogAddDate.setText("Date:");

        txtBlogPostDate.setPreferredSize(new java.awt.Dimension(130, 30));

        lblBlogPostTitle.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblBlogPostTitle.setText("Blog Title:");

        txtBlogPostTitle.setPreferredSize(new java.awt.Dimension(130, 30));

        lblBlogPostField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblBlogPostField.setText("Field of Post:");

        txtBlogPostField.setPreferredSize(new java.awt.Dimension(130, 30));

        txtAreaBlogPostDescription.setColumns(20);
        txtAreaBlogPostDescription.setRows(5);
        txtAreaBlogPostDescription.setPreferredSize(new java.awt.Dimension(130, 30));
        jScrollPane1.setViewportView(txtAreaBlogPostDescription);

        lblBlogPostDescrp.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblBlogPostDescrp.setText("Description:");

        btnBlogPublish.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBlogPublish.setText("Publish");
        btnBlogPublish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlogPublishActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(lblBlogPostHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBlogPostDescrp, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBlogPublish, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBlogPostTitle)
                            .addComponent(lblBlogAddDate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBlogPostDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBlogPostTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBlogPostField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBlogPostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblBlogPostHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBlogAddDate)
                    .addComponent(txtBlogPostDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBlogPostDescrp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBlogPostTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBlogPostTitle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBlogPostField)
                            .addComponent(txtBlogPostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBlogPublish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBlogPublishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlogPublishActionPerformed
        // Gather data from form fields
        String blogTitle = txtBlogPostTitle.getText().trim();
        String blogDate = txtBlogPostDate.getText().trim();
        String blogField = txtBlogPostField.getText().trim();
        String blogDescription = txtAreaBlogPostDescription.getText().trim();
        
        // Validate inputs
        if (blogTitle.isEmpty() || blogDate.isEmpty() || blogField.isEmpty() || blogDescription.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled out", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validate date format (YYYY-MM-DD)
        if (!blogDate.matches("\\d{4}-\\d{2}-\\d{2}")) {
            JOptionPane.showMessageDialog(this, "Date must be in the format YYYY-MM-DD", "Date Format Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Create a new document for MongoDB
        Document blogPost = new Document()
            .append("blogPostTitle", blogTitle)
            .append("blogPostDate", blogDate)
            .append("blogPostField", blogField)
            .append("blogPostDescription", blogDescription)
            .append("doctorId", doctorId.toHexString()); // Assuming doctorId is an ObjectId

        // Insert the new document into the "Blog" collection
        try {
            blogCollection.insertOne(blogPost);
            JOptionPane.showMessageDialog(this, "Blog post published successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            
            // Clear the text fields after successful insertion
            txtBlogPostTitle.setText("");
            txtBlogPostDate.setText("");
            txtBlogPostField.setText("");
            txtAreaBlogPostDescription.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Failed to publish blog post: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBlogPublishActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBlogPublish;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBlogAddDate;
    private javax.swing.JLabel lblBlogPostDescrp;
    private javax.swing.JLabel lblBlogPostField;
    private javax.swing.JLabel lblBlogPostHeader;
    private javax.swing.JLabel lblBlogPostTitle;
    private javax.swing.JTextArea txtAreaBlogPostDescription;
    private javax.swing.JTextField txtBlogPostDate;
    private javax.swing.JTextField txtBlogPostField;
    private javax.swing.JTextField txtBlogPostTitle;
    // End of variables declaration//GEN-END:variables

}
