/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import database.CRUDOperations;
import database.Connection;
import model.Business.Business;
import org.bson.Document;
import org.bson.types.ObjectId;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;


public class TrainingCenterAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrainingCenterAdminJPanel
     */
    JPanel adminLayout;
    MongoDatabase database;
    Business business;
    MongoCollection<Document> trainingCenterCollection;
    MongoCollection<Document> userCollection;
    CRUDOperations crudOperations = new CRUDOperations();

    public TrainingCenterAdminJPanel(JPanel adminLayout, MongoDatabase database, Business business) {
        initComponents();
        this.adminLayout = adminLayout;
        this.database = new Connection().connectToDatabase();
        this.business = business;

        trainingCenterCollection = this.database.getCollection("TrainingCenter");
        userCollection = this.database.getCollection("UserLogin");
        populateTrainingCenterTable();
    }

    private void populateTrainingCenterTable() {
        DefaultTableModel model = (DefaultTableModel) tblTrainingCenterAdminDetails.getModel();
        model.setRowCount(0);

        FindIterable<Document> trainingCenterDetails = trainingCenterCollection.find();
        for (Document document : trainingCenterDetails) {
            org.bson.Document user = crudOperations.getFirstRecordByKey("_id", new ObjectId(document.get("trainingcenterAdminId").toString()), userCollection);

            model.addRow(new Object[]{
                    document.get("trainingcenterName"),
                    document.get("trainingcenterLocation"),
                    document.get("trainingcenterContact"),
                    document.get("trainingcenterEmail"),
                    user.get("name")
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTrainingCenterAdminDetails = new javax.swing.JTable();
        btnAddTrainingCenter = new javax.swing.JButton();

        tblTrainingCenterAdminDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Location", "Contact", "Email", "Manager Name"
            }
        ));
        jScrollPane1.setViewportView(tblTrainingCenterAdminDetails);

        btnAddTrainingCenter.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnAddTrainingCenter.setText("Add Training Center");
        btnAddTrainingCenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTrainingCenterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddTrainingCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnAddTrainingCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTrainingCenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTrainingCenterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddTrainingCenterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTrainingCenter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTrainingCenterAdminDetails;
    // End of variables declaration//GEN-END:variables
}
