/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DoctorInstructor;

import ui.Doctor.*;
import java.awt.CardLayout;
import ui.MainLoginJPanel;


public class DoctorInstructorMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form doctorWorkAreaJPanel
     */
    public DoctorInstructorMainJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DoctorInstSplitPane = new javax.swing.JSplitPane();
        DoctorControlPaneJPanel = new javax.swing.JPanel();
        btnDoctorInstViewReport = new javax.swing.JButton();
        btnDoctorInstViewStatus = new javax.swing.JButton();
        btnDoctorInstUpdateStatus = new javax.swing.JButton();
        DoctorCardWorkAreaJPanel = new javax.swing.JPanel();

        DoctorInstSplitPane.setDividerLocation(100);
        DoctorInstSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        btnDoctorInstViewReport.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnDoctorInstViewReport.setText("View Report");
        btnDoctorInstViewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorInstViewReportActionPerformed(evt);
            }
        });

        btnDoctorInstViewStatus.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnDoctorInstViewStatus.setText("View Status");
        btnDoctorInstViewStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorInstViewStatusActionPerformed(evt);
            }
        });

        btnDoctorInstUpdateStatus.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnDoctorInstUpdateStatus.setText("Update Status");
        btnDoctorInstUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorInstUpdateStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DoctorControlPaneJPanelLayout = new javax.swing.GroupLayout(DoctorControlPaneJPanel);
        DoctorControlPaneJPanel.setLayout(DoctorControlPaneJPanelLayout);
        DoctorControlPaneJPanelLayout.setHorizontalGroup(
            DoctorControlPaneJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorControlPaneJPanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnDoctorInstViewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnDoctorInstUpdateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnDoctorInstViewStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        DoctorControlPaneJPanelLayout.setVerticalGroup(
            DoctorControlPaneJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoctorControlPaneJPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(DoctorControlPaneJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoctorInstViewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoctorInstUpdateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoctorInstViewStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        DoctorInstSplitPane.setTopComponent(DoctorControlPaneJPanel);

        DoctorCardWorkAreaJPanel.setLayout(new java.awt.CardLayout());
        DoctorInstSplitPane.setRightComponent(DoctorCardWorkAreaJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DoctorInstSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DoctorInstSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(530, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoctorInstViewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorInstViewReportActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnDoctorInstViewReportActionPerformed

    private void btnDoctorInstViewStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorInstViewStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoctorInstViewStatusActionPerformed

    private void btnDoctorInstUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorInstUpdateStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoctorInstUpdateStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DoctorCardWorkAreaJPanel;
    private javax.swing.JPanel DoctorControlPaneJPanel;
    private javax.swing.JSplitPane DoctorInstSplitPane;
    private javax.swing.JButton btnDoctorInstUpdateStatus;
    private javax.swing.JButton btnDoctorInstViewReport;
    private javax.swing.JButton btnDoctorInstViewStatus;
    // End of variables declaration//GEN-END:variables
}
