/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Blogs;

import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import database.Connection;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Business.Business;
import org.bson.Document;
import org.bson.types.ObjectId;

public class BlogViewJPanel extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    Business business;
    MongoDatabase database;
    ObjectId blogId;
    private final JFileChooser fileChooser = new JFileChooser();
    ImageIcon productImage;
    MongoCollection<Document> blogCollection;
    MongoCollection<Document> doctorCollection;
    /**
     * Creates new form blogViewJPanel
     */
    public BlogViewJPanel(JPanel cardSequencePanel, MongoDatabase database, Business business, ObjectId blogId) {
        initComponents();
        this.CardSequencePanel = cardSequencePanel;
        this.database = new Connection().connectToDatabase();
        this.business = business;
        this.blogId = blogId;
        this.blogCollection = this.database.getCollection("Blog");
        this.doctorCollection = this.database.getCollection("Doctor");
        loadBlogDetails();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBlogViewTitle = new javax.swing.JLabel();
        txtBlogPostTitle = new javax.swing.JTextField();
        lblBlogViewField = new javax.swing.JLabel();
        txtBlogPostField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaBlogViewDescription = new javax.swing.JTextArea();
        lblBlogViewDate = new javax.swing.JLabel();
        txtBlogPostDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        lblBlogViewTitle.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblBlogViewTitle.setText("Title:");

        txtBlogPostTitle.setPreferredSize(new java.awt.Dimension(130, 30));

        lblBlogViewField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblBlogViewField.setText("Field of Post:");

        txtBlogPostField.setPreferredSize(new java.awt.Dimension(130, 30));

        txtAreaBlogViewDescription.setColumns(20);
        txtAreaBlogViewDescription.setRows(5);
        txtAreaBlogViewDescription.setPreferredSize(new java.awt.Dimension(130, 30));
        jScrollPane1.setViewportView(txtAreaBlogViewDescription);

        lblBlogViewDate.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblBlogViewDate.setText("Date Posted:");

        txtBlogPostDate.setPreferredSize(new java.awt.Dimension(130, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BLOG VIEW PANEL");

        btnBack.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBlogViewTitle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBlogPostTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblBlogViewDate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBlogPostDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 149, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBlogViewField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBlogPostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBlogPostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBlogViewField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBlogViewTitle)
                    .addComponent(txtBlogPostTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBlogViewDate)
                    .addComponent(txtBlogPostDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBlogViewDate;
    private javax.swing.JLabel lblBlogViewField;
    private javax.swing.JLabel lblBlogViewTitle;
    private javax.swing.JTextArea txtAreaBlogViewDescription;
    private javax.swing.JTextField txtBlogPostDate;
    private javax.swing.JTextField txtBlogPostField;
    private javax.swing.JTextField txtBlogPostTitle;
    // End of variables declaration//GEN-END:variables

    private void loadBlogDetails() {
        if (blogId == null) {
            JOptionPane.showMessageDialog(this, "Invalid blog ID.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Fetch the blog document
        Document blog = blogCollection.find(Filters.eq("_id", blogId)).first();
        if (blog == null) {
            JOptionPane.showMessageDialog(this, "Blog not found.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Set blog details to fields
        txtBlogPostTitle.setText(blog.getString("blogPostTitle"));
        txtBlogPostField.setText(blog.getString("blogPostField"));
        txtBlogPostDate.setText(blog.getString("blogPostDate"));
        txtAreaBlogViewDescription.setText(blog.getString("blogPostDescription"));

        // Retrieve the doctor's name
        String doctorId = blog.getString("doctorId");
        Document doctor = doctorCollection.find(Filters.eq("_id", new ObjectId(doctorId))).first();
        String doctorName = (doctor != null) ? doctor.getString("doctorName") : "Unknown Doctor";

        // Optionally display the doctor's name if needed
        // For example, you could have a label to display it or include it in another text field
        // lblDoctorName.setText("Published by: " + doctorName);
    }
}
