/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Doctor;

import com.mongodb.client.MongoDatabase;
import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Business.Business;
import model.Personnel.Doctor;
import ui.MainLoginJPanel;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import java.util.ArrayList;
import java.util.List;
import database.CRUDOperations;
import database.Connection;
import model.TrainingCenter.TrainingCenter;
import static org.bouncycastle.asn1.x509.X509ObjectIdentifiers.organization;
import org.bson.Document;
import org.bson.types.ObjectId;
import ui.Blogs.BlogHomeJPanel;
import ui.Patients.PatientDetailsJPanel;


public class DoctorMainJPanel extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    Business business;
    Doctor doctor;
    MongoDatabase database;

    /**
     * Creates new form doctorWorkAreaJPanel
     */
    public DoctorMainJPanel(JPanel cardSequencePanel, Doctor doctor, MongoDatabase database, Business business) {
        initComponents();
        this.CardSequencePanel = cardSequencePanel;
        this.doctor = doctor;
        this.database = database;
        this.business = business;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        DoctorCardControlPaneJPanel = new javax.swing.JPanel();
        btnDoctorChat = new javax.swing.JButton();
        btnDoctorGetPatient = new javax.swing.JButton();
        btnDoctorBlog = new javax.swing.JButton();
        DoctorCardWorkAreaJPanel = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(100);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        btnDoctorChat.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnDoctorChat.setText("Chat");
        btnDoctorChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorChatActionPerformed(evt);
            }
        });

        btnDoctorGetPatient.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnDoctorGetPatient.setText("Patient Details");
        btnDoctorGetPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorGetPatientActionPerformed(evt);
            }
        });

        btnDoctorBlog.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnDoctorBlog.setText("Blog");
        btnDoctorBlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorBlogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DoctorCardControlPaneJPanelLayout = new javax.swing.GroupLayout(DoctorCardControlPaneJPanel);
        DoctorCardControlPaneJPanel.setLayout(DoctorCardControlPaneJPanelLayout);
        DoctorCardControlPaneJPanelLayout.setHorizontalGroup(
            DoctorCardControlPaneJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorCardControlPaneJPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnDoctorChat, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199)
                .addComponent(btnDoctorBlog, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDoctorGetPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        DoctorCardControlPaneJPanelLayout.setVerticalGroup(
            DoctorCardControlPaneJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoctorCardControlPaneJPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(DoctorCardControlPaneJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoctorChat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoctorGetPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoctorBlog, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jSplitPane1.setTopComponent(DoctorCardControlPaneJPanel);

        DoctorCardWorkAreaJPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(DoctorCardWorkAreaJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoctorChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorChatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoctorChatActionPerformed

    private void btnDoctorGetPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorGetPatientActionPerformed
        // TODO add your handling code here:'
   
        PatientDetailsJPanel patientDetailsJPanel = new PatientDetailsJPanel(DoctorCardWorkAreaJPanel, database, business, doctor.getDoctorId());
        DoctorCardWorkAreaJPanel.add("patientDetailsJPanel", patientDetailsJPanel);
        CardLayout layout = (CardLayout) DoctorCardWorkAreaJPanel.getLayout();
        layout.next(DoctorCardWorkAreaJPanel);
    }//GEN-LAST:event_btnDoctorGetPatientActionPerformed

    private void btnDoctorBlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorBlogActionPerformed
        // TODO add your handling code here:
        BlogHomeJPanel blogmainJPanel = new BlogHomeJPanel(DoctorCardWorkAreaJPanel, database, business, doctor.getDoctorId());
        DoctorCardWorkAreaJPanel.add("blogmainJPanel", blogmainJPanel);
        CardLayout layout = (CardLayout) DoctorCardWorkAreaJPanel.getLayout();
        layout.next(DoctorCardWorkAreaJPanel);
    }//GEN-LAST:event_btnDoctorBlogActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DoctorCardControlPaneJPanel;
    private javax.swing.JPanel DoctorCardWorkAreaJPanel;
    private javax.swing.JButton btnDoctorBlog;
    private javax.swing.JButton btnDoctorChat;
    private javax.swing.JButton btnDoctorGetPatient;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
