/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TrainingCenter;

import com.mongodb.client.MongoDatabase;
import database.Connection;
import javax.swing.JPanel;
import model.Business.Business;
import model.TrainingCenter.TrainingCenter;


public class AddResidentDoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddResidentDoctorJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    TrainingCenter trainingcenter;
    MongoDatabase database;
    public AddResidentDoctorJPanel(JPanel cardSequencePanel,TrainingCenter trainingcenter,MongoDatabase database, Business business) {
        initComponents();
        this.CardSequencePanel = cardSequencePanel;
        this.trainingcenter = trainingcenter;
        this.database = new Connection().connectToDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtResidentName = new javax.swing.JTextField();
        txtResidentDoctorSpecialization = new javax.swing.JTextField();
        lblResidentDoctorName = new javax.swing.JLabel();
        lblResidentDoctorNumber = new javax.swing.JLabel();
        btnSaveCourse = new javax.swing.JButton();
        hospitalNameComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(241, 206, 255));

        lblResidentDoctorName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblResidentDoctorName.setText("Name :");

        lblResidentDoctorNumber.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblResidentDoctorNumber.setText("Specialization :");

        btnSaveCourse.setBackground(new java.awt.Color(150, 83, 178));
        btnSaveCourse.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnSaveCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveCourse.setText("Save");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Hospital :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSaveCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblResidentDoctorNumber)
                            .addComponent(lblResidentDoctorName)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hospitalNameComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtResidentName)
                            .addComponent(txtResidentDoctorSpecialization, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))))
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblResidentDoctorName)
                    .addComponent(txtResidentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResidentDoctorNumber)
                    .addComponent(txtResidentDoctorSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hospitalNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addComponent(btnSaveCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveCourse;
    private javax.swing.JComboBox<String> hospitalNameComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblResidentDoctorName;
    private javax.swing.JLabel lblResidentDoctorNumber;
    private javax.swing.JTextField txtResidentDoctorSpecialization;
    private javax.swing.JTextField txtResidentName;
    // End of variables declaration//GEN-END:variables
}
