/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TrainingCenter;


public class AddTrainingCenterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddTrainingCenterJPanel
     */
    public AddTrainingCenterJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTrainingCentreEmail = new javax.swing.JTextField();
        btnBackTrainingCentre = new javax.swing.JButton();
        lblTrainingCentreName = new javax.swing.JLabel();
        lblCourseNumber = new javax.swing.JLabel();
        lblTrainingCentreContact = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblTrainingCentreEmail = new javax.swing.JLabel();
        lblCourseInstructor = new javax.swing.JLabel();
        lblTrainingCentreManagerPassword = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        txtTrainingCentreLocation = new javax.swing.JTextField();
        txtTrainingCentreContact = new javax.swing.JTextField();
        txtTrainingCentreManagerName = new javax.swing.JTextField();
        txtTrainingCentreManagerPassword = new javax.swing.JTextField();
        lblTrainingCentreDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaTrainingCentreDescription = new javax.swing.JTextArea();
        btnAddTrainingCentre1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(241, 206, 255));

        btnBackTrainingCentre.setBackground(new java.awt.Color(0, 0, 0));
        btnBackTrainingCentre.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBackTrainingCentre.setForeground(new java.awt.Color(255, 255, 255));
        btnBackTrainingCentre.setText("BACK");
        btnBackTrainingCentre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackTrainingCentreActionPerformed(evt);
            }
        });

        lblTrainingCentreName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblTrainingCentreName.setText("Training Centre Name :");

        lblCourseNumber.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCourseNumber.setText("Training Centre Location:");

        lblTrainingCentreContact.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblTrainingCentreContact.setText("Contact:");

        lblTitle.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Add Training Centre");

        lblTrainingCentreEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblTrainingCentreEmail.setText("Training Centre Email :");

        lblCourseInstructor.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCourseInstructor.setText("Manager Name :");

        lblTrainingCentreManagerPassword.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblTrainingCentreManagerPassword.setText("Manager Password :");

        lblTrainingCentreDescription.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblTrainingCentreDescription.setText("Training Centre Description :");

        txtAreaTrainingCentreDescription.setColumns(20);
        txtAreaTrainingCentreDescription.setRows(5);
        txtAreaTrainingCentreDescription.setWrapStyleWord(true);
        txtAreaTrainingCentreDescription.setPreferredSize(new java.awt.Dimension(130, 30));
        jScrollPane1.setViewportView(txtAreaTrainingCentreDescription);

        btnAddTrainingCentre1.setBackground(new java.awt.Color(150, 83, 178));
        btnAddTrainingCentre1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnAddTrainingCentre1.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTrainingCentre1.setText("ADD TRAINING CENTRE");
        btnAddTrainingCentre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTrainingCentre1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBackTrainingCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTrainingCentreManagerPassword)
                            .addComponent(lblCourseInstructor)
                            .addComponent(lblTrainingCentreContact)
                            .addComponent(lblTrainingCentreEmail)
                            .addComponent(lblTrainingCentreDescription)
                            .addComponent(lblCourseNumber)
                            .addComponent(lblTrainingCentreName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTrainingCentreEmail)
                            .addComponent(txtCourseName)
                            .addComponent(txtTrainingCentreLocation)
                            .addComponent(txtTrainingCentreContact)
                            .addComponent(txtTrainingCentreManagerName)
                            .addComponent(txtTrainingCentreManagerPassword)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddTrainingCentre1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnBackTrainingCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTrainingCentreName))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseNumber)
                    .addComponent(txtTrainingCentreLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrainingCentreContact)
                    .addComponent(txtTrainingCentreContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseInstructor)
                    .addComponent(txtTrainingCentreManagerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrainingCentreManagerPassword)
                    .addComponent(txtTrainingCentreManagerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTrainingCentreEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTrainingCentreEmail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTrainingCentreDescription)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnAddTrainingCentre1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackTrainingCentreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackTrainingCentreActionPerformed
        // TODO add your handling code here:
        // Retrieve inputs from GUI components
        
    }//GEN-LAST:event_btnBackTrainingCentreActionPerformed

    private void btnAddTrainingCentre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTrainingCentre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddTrainingCentre1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTrainingCentre1;
    private javax.swing.JButton btnBackTrainingCentre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourseInstructor;
    private javax.swing.JLabel lblCourseNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTrainingCentreContact;
    private javax.swing.JLabel lblTrainingCentreDescription;
    private javax.swing.JLabel lblTrainingCentreEmail;
    private javax.swing.JLabel lblTrainingCentreManagerPassword;
    private javax.swing.JLabel lblTrainingCentreName;
    private javax.swing.JTextArea txtAreaTrainingCentreDescription;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtTrainingCentreContact;
    private javax.swing.JTextField txtTrainingCentreEmail;
    private javax.swing.JTextField txtTrainingCentreLocation;
    private javax.swing.JTextField txtTrainingCentreManagerName;
    private javax.swing.JTextField txtTrainingCentreManagerPassword;
    // End of variables declaration//GEN-END:variables
}
