/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.FoodFactory;

import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;

import database.CRUDOperations;
import database.Connection;
import java.awt.CardLayout;

import database.Connection;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Business.Business;


<<<<<<< HEAD:FoodNetwork/FoodNetwork/FoodNetwork/src/main/java/ui/FoodProcessorUI/FoodItemsJPanel.java
import model.FoodProcessItem.FoodProcessItemDirectory;
=======
import model.FoodFactory.FoodProcessItemDirectory;
>>>>>>> NilayRaut:Food Network/src/main/java/ui/FoodFactory/FoodItemsJPanel.java
import org.bson.Document;
import org.bson.types.ObjectId;

import org.bson.Document;
import org.bson.types.ObjectId;
import ui.Hospital.AddMedicalEquipmentJPanel;


public class FoodItemsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EquipmentsJPanel
     */
    JPanel cardSequencePanel;
    MongoDatabase database;
    FoodProcessItemDirectory medicalEquipmentSupplier;
    Business business;
    MongoCollection<FoodProcessItemDirectory> equipmentSupplierCollection;
    MongoCollection<Document> supplierEquipmentCollection;
    MongoCollection<Document> medicalEquipmentCollection;
    CRUDOperations crud = new CRUDOperations();
    
    public FoodItemsJPanel(JPanel cardSequencePanel, FoodProcessItemDirectory medicalEquipmentSupplier, MongoDatabase database, Business business) {
        initComponents();
        this.cardSequencePanel = cardSequencePanel;
        this.medicalEquipmentSupplier = medicalEquipmentSupplier;
        this.database = new Connection().connectToDatabase();;
        this.business = business;
        this.supplierEquipmentCollection = this.database.getCollection("SupplierEquipment");
        this.medicalEquipmentCollection = this.database.getCollection("MedicalEquipment");
        CRUDOperations crud = new CRUDOperations();
        populateTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblEquipments.getModel();
        model.setRowCount(0);
        String supplierId = medicalEquipmentSupplier.getId().toString();
        FindIterable<Document> findIterable = crud.getRecordsByKey("supplierId", supplierId, supplierEquipmentCollection);
        MongoCursor<Document> cursor = findIterable.iterator();
        try {
            while (cursor.hasNext()) {
                Document doc = cursor.next();
                Object[] row = new Object[4];
                ObjectId equipmentId = new ObjectId(doc.getString("equipmentId"));
                Document equipmentDoc = crud.getFirstRecordByKey("_id", equipmentId, medicalEquipmentCollection);
                row[0] = equipmentDoc.getString("equipmentName");
                row[1] = equipmentDoc.getString("equipmentType");
                row[2] = equipmentDoc.getString("equipmentDescription");
                row[3] = equipmentDoc.getString("equipmentPurpose");
                model.addRow(row);
            }
        } finally {
            cursor.close();
        }

    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEquipments = new javax.swing.JTable();
        btnAddNewEquipment = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 223, 164));

        tblEquipments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Type", "Description", "Purpose"
            }
        ));
        jScrollPane1.setViewportView(tblEquipments);

        btnAddNewEquipment.setBackground(new java.awt.Color(255, 102, 0));
        btnAddNewEquipment.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnAddNewEquipment.setForeground(new java.awt.Color(255, 255, 255));
        btnAddNewEquipment.setText("Add Equipment");
        btnAddNewEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewEquipmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnAddNewEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnAddNewEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewEquipmentActionPerformed
        // TODO add your handling code here:
        AdditemJPanel addJPanel = new AdditemJPanel (cardSequencePanel, database, business);
        cardSequencePanel.add("AddJPanel", addJPanel);
        CardLayout layout = (CardLayout) cardSequencePanel.getLayout();
        layout.next(cardSequencePanel);
    }//GEN-LAST:event_btnAddNewEquipmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewEquipment;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEquipments;
    // End of variables declaration//GEN-END:variables
}
