/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Hospital;

import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;

import javax.swing.JPanel;

import database.CRUDOperations;
import database.Connection;
import model.Business.Business;
import model.Hospital.Hospital;
import org.bson.Document;
import org.bson.types.ObjectId;


public class AddMedicalEquipmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddMedicalEquipmentJPanel
     */
    JPanel HospitalCardLayout;
    Hospital hospital;
    MongoDatabase database;
    Business business;
    MongoCollection<Document> supplierCollection;
    MongoCollection<Document> equipmentCollection;
    MongoCollection<Document> supplierEquipmentCollection;
    MongoCollection<Document> requestEquipmentCollection;
    CRUDOperations crudOperations = new CRUDOperations();

    public AddMedicalEquipmentJPanel(JPanel HospitalCardLayout, Hospital hospital, MongoDatabase databases, Business business) {
        initComponents();
        this.HospitalCardLayout = HospitalCardLayout;
        this.hospital = hospital;
        this.database = new Connection().connectToDatabase();
        this.business = business;
        this.supplierCollection = database.getCollection("Supplier");
        this.equipmentCollection = database.getCollection("MedicalEquipment");
        this.supplierEquipmentCollection = database.getCollection("SupplierEquipment");
        this.requestEquipmentCollection = database.getCollection("RequestEquipment");

        //populateComboBox();
        populateSupplierComboBox();
        populateEquipmentComboBox();
        populatePurpose();
    }

    private void populatePurpose() {
//        show selected equipments pupose
        String SelectedEquipment = cmbEquipments.getSelectedItem().toString();
        Document equipment = crudOperations.getFirstRecordByKey("equipmentName", SelectedEquipment, equipmentCollection);
        txtPurpose.setText(equipment.getString("equipmentPurpose"));
    }

    private void populateEquipmentComboBox() {
        String SelectedSupplier = cmbSuppliers.getSelectedItem().toString();
        Document supplier = crudOperations.getFirstRecordByKey("supplierName", SelectedSupplier, supplierCollection);
        System.out.println(supplier.get("_id") + "cfgvhbj");
        FindIterable<Document> supplierEquipmentList = crudOperations.getRecordsByKey("supplierId", String.valueOf(supplier.get("_id")), supplierEquipmentCollection);
        for (Document supplierEquipment : supplierEquipmentList) {
            System.out.println(supplierEquipment.get("equipmentId") + "dfcvv");
            Document equipment = crudOperations.getFirstRecordByKey("_id", new ObjectId(supplierEquipment.get("equipmentId").toString()), equipmentCollection);
            cmbEquipments.addItem(equipment.getString("equipmentName"));
        }
    }

    private void populateSupplierComboBox() {
        FindIterable<Document> supplierList = crudOperations.getRecordsByKey("organizationType", "Supplier", supplierCollection);
        for (Document supplier : supplierList) {
            cmbSuppliers.addItem(supplier.getString("supplierName"));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSubmitRequest = new javax.swing.JButton();
        lblBlogPostHeader = new javax.swing.JLabel();
        txtPurpose = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbSuppliers = new javax.swing.JComboBox<>();
        cmbEquipments = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 228, 230));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setText("Equipment Purpose");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Equipment Name");

        btnSubmitRequest.setBackground(new java.awt.Color(244, 63, 94));
        btnSubmitRequest.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnSubmitRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmitRequest.setText("Submit Request");
        btnSubmitRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRequestActionPerformed(evt);
            }
        });

        lblBlogPostHeader.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblBlogPostHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBlogPostHeader.setText("Request New Equipment");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Equipment Supplier");

        cmbSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSuppliersActionPerformed(evt);
            }
        });

        cmbEquipments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEquipmentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPurpose, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(cmbSuppliers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbEquipments, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSubmitRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lblBlogPostHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSubmitRequest, cmbEquipments, cmbSuppliers, txtPurpose});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblBlogPostHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbEquipments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPurpose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addComponent(btnSubmitRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRequestActionPerformed
        // TODO add your handling code here:
        String SelectedSupplier = cmbSuppliers.getSelectedItem().toString();
        String SelectedEquipment = cmbEquipments.getSelectedItem().toString();
        Document supplier = crudOperations.getFirstRecordByKey("supplierName", SelectedSupplier, supplierCollection);
        Document equipment = crudOperations.getFirstRecordByKey("equipmentName", SelectedEquipment, equipmentCollection);

        Document request = new Document();
        request.append("hospitalId", hospital.getHospitalId().toString());
        request.append("supplierId", supplier.get("_id").toString());
        request.append("equipmentId", equipment.get("_id").toString());
        request.append("status", "Pending");

        crudOperations.insertDocument(request, requestEquipmentCollection);


    }//GEN-LAST:event_btnSubmitRequestActionPerformed

    private void cmbSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSuppliersActionPerformed
        // TODO add your handling code here:
        cmbEquipments.removeAllItems();
        populateEquipmentComboBox();
    }//GEN-LAST:event_cmbSuppliersActionPerformed

    private void cmbEquipmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEquipmentsActionPerformed
        // TODO add your handling code here:
        populatePurpose();
    }//GEN-LAST:event_cmbEquipmentsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmitRequest;
    private javax.swing.JComboBox<String> cmbEquipments;
    private javax.swing.JComboBox<String> cmbSuppliers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblBlogPostHeader;
    private javax.swing.JTextField txtPurpose;
    // End of variables declaration//GEN-END:variables
}
