/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import database.Connection;
import database.DataBaseConnection;
import java.awt.CardLayout;
import model.Business.Business;
import model.Business.ConfigureABusiness;
import org.bson.Document;
import java.io.IOException;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


public class LoginJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginJFrame
     */
    MongoDatabase database;
    MongoCollection<Document> collection;
    Business business;

    public LoginJFrame() {
        initComponents();
        business = ConfigureABusiness.initialize();
        setResizable(false);
        this.database = new Connection().connectToDatabase();
        this.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);

        ImageIcon icon = new ImageIcon("./PharmacyHomeImage.jpg");
        JLabel imageLabel = new JLabel(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginSplitFrame = new javax.swing.JSplitPane();
        CardSequencePanel = new javax.swing.JPanel();
        loginMenuJPanel = new javax.swing.JPanel();
        btnDistributorLogin = new javax.swing.JButton();
        btnRetailerLogin = new javax.swing.JButton();
        btnFoodProcessorLogin = new javax.swing.JButton();
        btnAdminLogin = new javax.swing.JButton();
        btnFarmerLogin = new javax.swing.JButton();
        btnRestaurantManagerLogin = new javax.swing.JButton();
        btnLivestockLogin = new javax.swing.JButton();
        btnWarehouseOperatorLogin1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginSplitFrame.setDividerLocation(201);

        CardSequencePanel.setLayout(new java.awt.CardLayout());
        LoginSplitFrame.setRightComponent(CardSequencePanel);

        btnDistributorLogin.setText("Distributor");
        btnDistributorLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDistributorLoginActionPerformed(evt);
            }
        });

        btnRetailerLogin.setText("Retailer");
        btnRetailerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetailerLoginActionPerformed(evt);
            }
        });

        btnFoodProcessorLogin.setText("Food Processor");
        btnFoodProcessorLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodProcessorLoginActionPerformed(evt);
            }
        });

        btnAdminLogin.setText("Admin");
        btnAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLoginActionPerformed(evt);
            }
        });

        btnFarmerLogin.setText("Farmer");
        btnFarmerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFarmerLoginActionPerformed(evt);
            }
        });

        btnRestaurantManagerLogin.setText("Restaurant Manager");
        btnRestaurantManagerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurantManagerLoginActionPerformed(evt);
            }
        });

        btnLivestockLogin.setText("Livestock");
        btnLivestockLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivestockLoginActionPerformed(evt);
            }
        });

        btnWarehouseOperatorLogin1.setText("Warehouse Operator");
        btnWarehouseOperatorLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWarehouseOperatorLogin1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginMenuJPanelLayout = new javax.swing.GroupLayout(loginMenuJPanel);
        loginMenuJPanel.setLayout(loginMenuJPanelLayout);
        loginMenuJPanelLayout.setHorizontalGroup(
            loginMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginMenuJPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(loginMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRestaurantManagerLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(loginMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnFarmerLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(btnFoodProcessorLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRetailerLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDistributorLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdminLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLivestockLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnWarehouseOperatorLogin1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        loginMenuJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdminLogin, btnDistributorLogin, btnFarmerLogin, btnFoodProcessorLogin, btnRestaurantManagerLogin, btnRetailerLogin});

        loginMenuJPanelLayout.setVerticalGroup(
            loginMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginMenuJPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnAdminLogin)
                .addGap(18, 18, 18)
                .addComponent(btnFarmerLogin)
                .addGap(18, 18, 18)
                .addComponent(btnFoodProcessorLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRetailerLogin)
                .addGap(18, 18, 18)
                .addComponent(btnDistributorLogin)
                .addGap(18, 18, 18)
                .addComponent(btnRestaurantManagerLogin)
                .addGap(18, 18, 18)
                .addComponent(btnLivestockLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnWarehouseOperatorLogin1)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        loginMenuJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdminLogin, btnDistributorLogin, btnFarmerLogin, btnFoodProcessorLogin, btnRestaurantManagerLogin, btnRetailerLogin});

        LoginSplitFrame.setLeftComponent(loginMenuJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoginSplitFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoginSplitFrame)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFarmerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFarmerLoginActionPerformed
        // TODO add your handling code here:
        goToLoginPage("Farm");

    }//GEN-LAST:event_btnFarmerLoginActionPerformed

    private void btnAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLoginActionPerformed
        // TODO add your handling code here:
        goToLoginPage("Admin");
    }//GEN-LAST:event_btnAdminLoginActionPerformed

    private void btnFoodProcessorLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoodProcessorLoginActionPerformed
        // TODO add your handling code here:
        goToLoginPage("FoodProcessor");
    }//GEN-LAST:event_btnFoodProcessorLoginActionPerformed

    private void btnRetailerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetailerLoginActionPerformed
        // TODO add your handling code here:
        goToLoginPage("Retailer");
    }//GEN-LAST:event_btnRetailerLoginActionPerformed

    private void btnDistributorLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDistributorLoginActionPerformed
        // TODO add your handling code here:
        goToLoginPage("Research");
    }//GEN-LAST:event_btnDistributorLoginActionPerformed

    private void btnRestaurantManagerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurantManagerLoginActionPerformed
        // TODO add your handling code here:
        goToLoginPage("Restaurant");
        System.out.println("Restaurant");
    }//GEN-LAST:event_btnRestaurantManagerLoginActionPerformed

    private void btnLivestockLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLivestockLoginActionPerformed
        // TODO add your handling code here:
        goToLoginPage("Doctor");
    }//GEN-LAST:event_btnLivestockLoginActionPerformed

    private void btnWarehouseOperatorLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWarehouseOperatorLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWarehouseOperatorLogin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginJFrame().setVisible(true);
            }
        });

        DataBaseConnection dbConnection = DataBaseConnection.connectToDatabase();

        // Create a new user record
        String name = "Alice";
        String dob = "1990-05-15"; // Example date of birth format (YYYY-MM-DD)
        String password = "securePassword123"; // Example password

        // Insert the user record into the database
        dbConnection.insertUser(name, dob, password);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardSequencePanel;
    private javax.swing.JSplitPane LoginSplitFrame;
    private javax.swing.JButton btnAdminLogin;
    private javax.swing.JButton btnDistributorLogin;
    private javax.swing.JButton btnFarmerLogin;
    private javax.swing.JButton btnFoodProcessorLogin;
    private javax.swing.JButton btnLivestockLogin;
    private javax.swing.JButton btnRestaurantManagerLogin;
    private javax.swing.JButton btnRetailerLogin;
    private javax.swing.JButton btnWarehouseOperatorLogin1;
    private javax.swing.JPanel loginMenuJPanel;
    // End of variables declaration//GEN-END:variables

    private void goToLoginPage(String role) {
        MainLoginJPanel mainLoginJPanel = new MainLoginJPanel(CardSequencePanel, business, role, database);
        CardSequencePanel.add("MainLoginJPanel", mainLoginJPanel);
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.next(CardSequencePanel);
    }
}
