/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import database.CRUDOperations;
import database.Connection;
import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Business.Business;
import org.bson.Document;


public class AddFarmerJPanel extends javax.swing.JPanel {
    JPanel AdminLayout;
    Business business;
    MongoDatabase database;
    MongoCollection<Document> retailerCollection;
    MongoCollection<Document> userCollection;
    CRUDOperations crudOperations = new CRUDOperations();

    /**
     * Creates new form AddTrainingCenterJPanel
     */
    public AddFarmerJPanel(JPanel adminLayout, MongoDatabase databases, Business business) {
        initComponents();
        this.AdminLayout = adminLayout;
        this.business = business;
        this.database = new Connection().connectToDatabase();
        retailerCollection = database.getCollection("Farm");
        userCollection = database.getCollection("UserLogin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFarmerEmail = new javax.swing.JTextField();
        btnBackRetailer = new javax.swing.JButton();
        lblfn = new javax.swing.JLabel();
        lblfl = new javax.swing.JLabel();
        lblfContact = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblFarmEmail = new javax.swing.JLabel();
        lblFarmer = new javax.swing.JLabel();
        lblFarmerPass = new javax.swing.JLabel();
        txtFarmName = new javax.swing.JTextField();
        txtFarmLocation = new javax.swing.JTextField();
        txtFarmContact = new javax.swing.JTextField();
        txtFarmerName = new javax.swing.JTextField();
        txtFarmPass = new javax.swing.JTextField();
        btnAddFarmer = new javax.swing.JButton();

        setBackground(new java.awt.Color(206, 238, 251));

        btnBackRetailer.setBackground(new java.awt.Color(0, 0, 0));
        btnBackRetailer.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBackRetailer.setForeground(new java.awt.Color(255, 255, 255));
        btnBackRetailer.setText("BACK");
        btnBackRetailer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackRetailerActionPerformed(evt);
            }
        });

        lblfn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblfn.setText("Farm Name :");

        lblfl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblfl.setText("Farm Location:");

        lblfContact.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblfContact.setText("Contact:");

        lblTitle.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Add Farmer");

        lblFarmEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblFarmEmail.setText("Farm Email :");

        lblFarmer.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblFarmer.setText("Farmer Name :");

        lblFarmerPass.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblFarmerPass.setText("Farmer Password :");
        lblFarmerPass.setToolTipText("");

        btnAddFarmer.setBackground(new java.awt.Color(0, 153, 204));
        btnAddFarmer.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnAddFarmer.setForeground(new java.awt.Color(255, 255, 255));
        btnAddFarmer.setText("ADD Farmer");
        btnAddFarmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFarmerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBackRetailer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFarmerPass)
                                    .addComponent(lblFarmer)
                                    .addComponent(lblfContact)
                                    .addComponent(lblFarmEmail)
                                    .addComponent(lblfl))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFarmerEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(txtFarmName)
                                    .addComponent(txtFarmLocation)
                                    .addComponent(txtFarmContact)
                                    .addComponent(txtFarmerName, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(txtFarmPass, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(btnAddFarmer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblfn)
                                .addGap(263, 263, 263))))
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnBackRetailer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblfn)
                    .addComponent(txtFarmName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfl)
                    .addComponent(txtFarmLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfContact)
                    .addComponent(txtFarmContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFarmer)
                    .addComponent(txtFarmerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFarmerPass)
                    .addComponent(txtFarmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFarmerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFarmEmail))
                .addGap(28, 28, 28)
                .addComponent(btnAddFarmer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackRetailerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackRetailerActionPerformed
        // TODO add your handling code here:
        // Retrieve inputs from GUI components
        FarmAdminJPanel farmAdminJPanel = new FarmAdminJPanel(AdminLayout, database, business);
        AdminLayout.add("FarmAdminJPanel", farmAdminJPanel);
        CardLayout layout = (CardLayout) AdminLayout.getLayout();
        layout.next(AdminLayout);
    }//GEN-LAST:event_btnBackRetailerActionPerformed

    private void btnAddFarmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFarmerActionPerformed
        // TODO add your handling code here:
    // Retrieve inputs from GUI components
    String farmName = txtFarmName.getText().trim();
    String farmLocation = txtFarmLocation.getText().trim();
    String farmContact = txtFarmContact.getText().trim();
    String farmerName = txtFarmerName.getText().trim();
    String farmerPassword = txtFarmPass.getText().trim();
    String farmerEmail = txtFarmerEmail.getText().trim();

    // Validate inputs
    if (farmName.isEmpty() || farmLocation.isEmpty() || farmContact.isEmpty()
            || farmerName.isEmpty() || farmerPassword.isEmpty() || farmerEmail.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "All fields are mandatory.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!farmerEmail.contains("@") || !farmerEmail.contains(".")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid email format.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Check if the farm already exists in the Farm collection
        Document existingFarm = retailerCollection.find(new Document("email", farmerEmail)).first();
        if (existingFarm != null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Farm with this email already exists.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check if the user already exists in the UserLogin collection
        Document existingUser = userCollection.find(new Document("email", farmerEmail)).first();
        if (existingUser != null) {
            javax.swing.JOptionPane.showMessageDialog(this, "User with this email already exists.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Add the farmer to the UserLogin collection
        Document user = new Document("email", farmerEmail)
                .append("username", farmerName)
                .append("password", farmerPassword)
                .append("role", "Farmer");
        userCollection.insertOne(user);

        // Retrieve the user ID for linking
        Document userDoc = userCollection.find(new Document("email", farmerEmail)).first();

        // Add the farm to the Farm collection
        Document farm = new Document("farmName", farmName)
                .append("farmlocation", farmLocation)
                .append("farmcontact", farmContact)
                .append("farmerName", farmerName)
                .append("farmemail", farmerEmail)
                .append("organizationType", "Farm")
                .append("FarmAdminId", String.valueOf(userDoc.getObjectId("_id")));

        retailerCollection.insertOne(farm);

        // Success message
        javax.swing.JOptionPane.showMessageDialog(this, "Farmer and Farm added successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // Clear the input fields
        txtFarmName.setText("");
        txtFarmLocation.setText("");
        txtFarmContact.setText("");
        txtFarmerName.setText("");
        txtFarmPass.setText("");
        txtFarmerEmail.setText("");

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error while adding farmer: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }






            
    }//GEN-LAST:event_btnAddFarmerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFarmer;
    private javax.swing.JButton btnBackRetailer;
    private javax.swing.JLabel lblFarmEmail;
    private javax.swing.JLabel lblFarmer;
    private javax.swing.JLabel lblFarmerPass;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblfContact;
    private javax.swing.JLabel lblfl;
    private javax.swing.JLabel lblfn;
    private javax.swing.JTextField txtFarmContact;
    private javax.swing.JTextField txtFarmLocation;
    private javax.swing.JTextField txtFarmName;
    private javax.swing.JTextField txtFarmPass;
    private javax.swing.JTextField txtFarmerEmail;
    private javax.swing.JTextField txtFarmerName;
    // End of variables declaration//GEN-END:variables
}
