/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import javax.swing.*;

import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import database.Connection;

import java.awt.CardLayout;

import model.Business.Business;
import org.bson.Document;

public class AddFoodFactoryJPanel extends javax.swing.JPanel {
    /**
     * Creates new form addMedicalEquipmentJPanel
     */
    JPanel AdminLayout;
    Business business;
    MongoDatabase database;
    MongoCollection<Document> supplierCollection;
    MongoCollection<Document> userCollection;

    public AddFoodFactoryJPanel(JPanel cardSequencePanel, MongoDatabase databases, Business business) {
        initComponents();
        this.AdminLayout = cardSequencePanel;
        this.business = business;
        this.database = new Connection().connectToDatabase();
        supplierCollection = database.getCollection("FoodProcessor");
        userCollection = database.getCollection("UserLogin");


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMedicalEquipmentList = new javax.swing.JPanel();
        lblAddMedicalEquipmentTitle = new javax.swing.JLabel();
        txtFactoryName = new javax.swing.JTextField();
        txtFactoryContact = new javax.swing.JTextField();
        lblFFAdress = new javax.swing.JLabel();
        lblFFName = new javax.swing.JLabel();
        btnAddNewFF = new javax.swing.JButton();
        txtFactoryAddress = new javax.swing.JTextField();
        lblFoodFactoryContact = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblManagerName = new javax.swing.JLabel();
        txtFactoryManagerName = new javax.swing.JTextField();
        lblFFManagerPassword = new javax.swing.JLabel();
        txtFactoryManagerPassword = new javax.swing.JTextField();
        lblFoodFactoryEmail = new javax.swing.JLabel();
        txtFactoryEmail = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        lblAddMedicalEquipmentTitle.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblAddMedicalEquipmentTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddMedicalEquipmentTitle.setText("ADD FOOD FACTORY DETAILS");
        lblAddMedicalEquipmentTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtFactoryName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFactoryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFactoryNameActionPerformed(evt);
            }
        });

        txtFactoryContact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFactoryContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFactoryContactActionPerformed(evt);
            }
        });

        lblFFAdress.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblFFAdress.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFFAdress.setText("Factory Address :");

        lblFFName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblFFName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFFName.setText("Factory Name :");

        btnAddNewFF.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnAddNewFF.setText("Add Factory");
        btnAddNewFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewFFActionPerformed(evt);
            }
        });

        txtFactoryAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFactoryAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFactoryAddressActionPerformed(evt);
            }
        });

        lblFoodFactoryContact.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblFoodFactoryContact.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFoodFactoryContact.setText("Factory Contact :");

        btnBack.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblManagerName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblManagerName.setText("Manager Name :");

        lblFFManagerPassword.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblFFManagerPassword.setText("Manager Password :");

        lblFoodFactoryEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblFoodFactoryEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFoodFactoryEmail.setText("Factory Email :");

        txtFactoryEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFactoryEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFactoryEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addMedicalEquipmentListLayout = new javax.swing.GroupLayout(addMedicalEquipmentList);
        addMedicalEquipmentList.setLayout(addMedicalEquipmentListLayout);
        addMedicalEquipmentListLayout.setHorizontalGroup(
            addMedicalEquipmentListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMedicalEquipmentListLayout.createSequentialGroup()
                .addGroup(addMedicalEquipmentListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addMedicalEquipmentListLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(addMedicalEquipmentListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddMedicalEquipmentTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addMedicalEquipmentListLayout.createSequentialGroup()
                                .addGroup(addMedicalEquipmentListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFFAdress)
                                    .addComponent(lblFFName)
                                    .addComponent(lblFoodFactoryContact))
                                .addGap(18, 18, 18)
                                .addGroup(addMedicalEquipmentListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFactoryName, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(txtFactoryAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(txtFactoryContact)))))
                    .addGroup(addMedicalEquipmentListLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addMedicalEquipmentListLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(addMedicalEquipmentListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFFManagerPassword)
                            .addComponent(lblManagerName))
                        .addGap(18, 18, 18)
                        .addGroup(addMedicalEquipmentListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddNewFF, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addMedicalEquipmentListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtFactoryManagerName, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                .addComponent(txtFactoryManagerPassword)))))
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(addMedicalEquipmentListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addMedicalEquipmentListLayout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addComponent(lblFoodFactoryEmail)
                    .addGap(18, 18, 18)
                    .addComponent(txtFactoryEmail)
                    .addGap(179, 179, 179)))
        );

        addMedicalEquipmentListLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddNewFF, txtFactoryAddress, txtFactoryContact, txtFactoryManagerName, txtFactoryName});

        addMedicalEquipmentListLayout.setVerticalGroup(
            addMedicalEquipmentListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addMedicalEquipmentListLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(lblAddMedicalEquipmentTitle)
                .addGap(59, 59, 59)
                .addGroup(addMedicalEquipmentListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addMedicalEquipmentListLayout.createSequentialGroup()
                        .addComponent(txtFactoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFactoryAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addMedicalEquipmentListLayout.createSequentialGroup()
                        .addComponent(lblFFName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFFAdress)))
                .addGap(18, 18, 18)
                .addGroup(addMedicalEquipmentListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFactoryContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoodFactoryContact))
                .addGap(50, 50, 50)
                .addGroup(addMedicalEquipmentListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManagerName)
                    .addComponent(txtFactoryManagerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addMedicalEquipmentListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFFManagerPassword)
                    .addComponent(txtFactoryManagerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnAddNewFF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(addMedicalEquipmentListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addMedicalEquipmentListLayout.createSequentialGroup()
                    .addContainerGap(259, Short.MAX_VALUE)
                    .addGroup(addMedicalEquipmentListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFactoryEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFoodFactoryEmail))
                    .addGap(204, 204, 204)))
        );

        addMedicalEquipmentListLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblFFAdress, lblFFName});

        addMedicalEquipmentListLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtFactoryAddress, txtFactoryContact, txtFactoryName});

        add(addMedicalEquipmentList, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void txtFactoryAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFactoryAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFactoryAddressActionPerformed

    private void btnAddNewFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewFFActionPerformed
       // Retrieve inputs from GUI components
    String factoryName = txtFactoryName.getText().trim();
    String factoryAddress = txtFactoryAddress.getText().trim();
    String factoryContact = txtFactoryContact.getText().trim();
    String factoryEmail = txtFactoryEmail.getText().trim();
    String managerName = txtFactoryManagerName.getText().trim();
    String managerPassword = txtFactoryManagerPassword.getText().trim();

    // Validate inputs
    if (factoryName.isEmpty() || factoryAddress.isEmpty() || factoryContact.isEmpty()
            || factoryEmail.isEmpty() || managerName.isEmpty() || managerPassword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "All fields are mandatory.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!factoryEmail.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
        JOptionPane.showMessageDialog(this, "Invalid email format.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Check if the factory email already exists in the FoodProcessor collection
        Document existingFactory = supplierCollection.find(new Document("factoryEmail", factoryEmail)).first();
        if (existingFactory != null) {
            JOptionPane.showMessageDialog(this, "A factory with this email already exists.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check if the manager username already exists in the UserLogin collection
        Document existingUser = userCollection.find(new Document("username", managerName)).first();
        if (existingUser != null) {
            JOptionPane.showMessageDialog(this, "Manager username already exists.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Add manager as a user in the UserLogin collection
        Document user = new Document("username", managerName)
                .append("password", managerPassword)
                .append("email", factoryEmail)
                .append("role", "FoodFactoryManager");
        userCollection.insertOne(user);

        // Retrieve the user ID of the newly added manager
        Document userDoc = userCollection.find(new Document("username", managerName)).first();

        // Add food factory details to the FoodProcessor collection
        Document foodFactory = new Document("foodprocessorName", factoryName)
                .append("factoryAddress", factoryAddress)
                .append("factoryContact", factoryContact)
                .append("factoryEmail", factoryEmail)
                .append("foodprocessorAdminId",  String.valueOf(userDoc.getObjectId("_id")))
                .append("organizationType", "Foodprocessor");

        supplierCollection.insertOne(foodFactory);

        // Success message
        JOptionPane.showMessageDialog(this, "Food Factory added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        // Clear input fields
        txtFactoryName.setText("");
        txtFactoryAddress.setText("");
        txtFactoryContact.setText("");
        txtFactoryEmail.setText("");
        txtFactoryManagerName.setText("");
        txtFactoryManagerPassword.setText("");

        // Navigate back to the previous screen
        btnBackActionPerformed(evt);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error while adding food factory: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAddNewFFActionPerformed

    private void txtFactoryContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFactoryContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFactoryContactActionPerformed

    private void txtFactoryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFactoryNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFactoryNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtFactoryEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFactoryEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFactoryEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addMedicalEquipmentList;
    private javax.swing.JButton btnAddNewFF;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblAddMedicalEquipmentTitle;
    private javax.swing.JLabel lblFFAdress;
    private javax.swing.JLabel lblFFManagerPassword;
    private javax.swing.JLabel lblFFName;
    private javax.swing.JLabel lblFoodFactoryContact;
    private javax.swing.JLabel lblFoodFactoryEmail;
    private javax.swing.JLabel lblManagerName;
    private javax.swing.JTextField txtFactoryAddress;
    private javax.swing.JTextField txtFactoryContact;
    private javax.swing.JTextField txtFactoryEmail;
    private javax.swing.JTextField txtFactoryManagerName;
    private javax.swing.JTextField txtFactoryManagerPassword;
    private javax.swing.JTextField txtFactoryName;
    // End of variables declaration//GEN-END:variables
}
