/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import database.CRUDOperations;
import database.Connection;
import java.awt.CardLayout;
import model.Business.Business;
import org.bson.Document;
import org.bson.types.ObjectId;
import ui.Patients.PatientReportJPanel;


public class HospitalAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalAdminJPanel
     */
    JPanel AdminLayout;
    MongoDatabase database;
    Business business;
    MongoCollection<Document> hospitalCollection;
    MongoCollection<Document> userCollection;
    CRUDOperations crudOperations = new CRUDOperations();

    public HospitalAdminJPanel(JPanel AdminLayout, MongoDatabase databases, Business business) {
        initComponents();
        this.AdminLayout = AdminLayout;
        this.database = new Connection().connectToDatabase();
        this.business = business;
        hospitalCollection = database.getCollection("Hospital");
        userCollection = database.getCollection("UserLogin");
        populateHospitalTable();
    }

    private void populateHospitalTable() {
        DefaultTableModel model = (DefaultTableModel) tblHospitalAdminDetails.getModel();
        model.setRowCount(0);

        FindIterable<Document> hospitalDetails = hospitalCollection.find();
        for (Document document : hospitalDetails) {
            org.bson.Document user = crudOperations.getFirstRecordByKey("_id", new ObjectId(document.get("hospitalAdminId").toString()), userCollection);

            model.addRow(new Object[]{
                document.get("hospitalName"),
                document.get("hospitalLocation"),
                document.get("hospitalContact"),
                document.get("hospitalEmail"),
                user.get("name")
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHospitalAdminDetails = new javax.swing.JTable();
        btnResidentDoctors = new javax.swing.JButton();
        btnDoctors = new javax.swing.JButton();
        btnAddHospital = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        tblHospitalAdminDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Location", "Contact", "Email", "Manager Name"
            }
        ));
        jScrollPane1.setViewportView(tblHospitalAdminDetails);

        btnResidentDoctors.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnResidentDoctors.setText("Resident Doctors");

        btnDoctors.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnDoctors.setText("Doctors");
        btnDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorsActionPerformed(evt);
            }
        });

        btnAddHospital.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnAddHospital.setText("Add Hospital");
        btnAddHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHospitalActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddHospital)
                                .addGap(18, 18, 18)
                                .addComponent(btnDoctors)
                                .addGap(18, 18, 18)
                                .addComponent(btnResidentDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddHospital, btnDoctors, btnResidentDoctors});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResidentDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoctors)
                    .addComponent(btnAddHospital))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddHospital, btnDoctors, btnResidentDoctors});

    }// </editor-fold>//GEN-END:initComponents

    private void btnAddHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHospitalActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnAddHospitalActionPerformed

    private void btnDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoctorsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        BusinessJPanel adminWorkAreaJPanel = new BusinessJPanel(AdminLayout, database, business);
        AdminLayout.add("AdminWorkAreaJPanel", adminWorkAreaJPanel);
        CardLayout layout = (CardLayout) AdminLayout.getLayout();
        layout.next(AdminLayout);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddHospital;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDoctors;
    private javax.swing.JButton btnResidentDoctors;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHospitalAdminDetails;
    // End of variables declaration//GEN-END:variables
}
