/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Retailer;

import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import database.CRUDOperations;
import database.Connection;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Business.Business;
import model.Retailer.Retailer;
import org.bson.Document;
import ui.Admin.RetailerAdminJPanel;

/**
 *
 * @author Danny
 */
public class AddProductJPanel extends javax.swing.JPanel {

    JPanel AdminLayout;
    Business business;
    MongoDatabase database;
    MongoCollection<Document> retailerCollection;
    MongoCollection<Document> userCollection;
    MongoCollection<Document> retailerProductCollection;

    CRUDOperations crudOperations = new CRUDOperations();
    Retailer retailer;

    /**
     * Creates new form AddTrainingCenterJPanel
     */
    public AddProductJPanel(JPanel adminLayout, MongoDatabase databases, Business business, Retailer retailer) {
        initComponents();
        this.AdminLayout = adminLayout;
        this.business = business;
        this.retailer = retailer;
        this.database = new Connection().connectToDatabase();
        retailerCollection = database.getCollection("Retailer");
        userCollection = database.getCollection("UserLogin");
        this.retailerProductCollection = this.database.getCollection("RetailerProduct");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBackRetailer = new javax.swing.JButton();
        lblRetailerName = new javax.swing.JLabel();
        lblRetailerLocation = new javax.swing.JLabel();
        lblPharmacyContact = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        txtSellingPrice = new javax.swing.JTextField();
        btnAddRetailer = new javax.swing.JButton();
        spnQuantity = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(206, 238, 251));

        btnBackRetailer.setBackground(new java.awt.Color(0, 0, 0));
        btnBackRetailer.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBackRetailer.setForeground(new java.awt.Color(255, 255, 255));
        btnBackRetailer.setText("BACK");
        btnBackRetailer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackRetailerActionPerformed(evt);
            }
        });

        lblRetailerName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblRetailerName.setText("Product Name :");

        lblRetailerLocation.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblRetailerLocation.setText("Selling Price:");

        lblPharmacyContact.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblPharmacyContact.setText("Quantity:");

        lblTitle.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Add Product");

        btnAddRetailer.setBackground(new java.awt.Color(0, 153, 204));
        btnAddRetailer.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnAddRetailer.setForeground(new java.awt.Color(255, 255, 255));
        btnAddRetailer.setText("ADD Product");
        btnAddRetailer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRetailerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBackRetailer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPharmacyContact)
                                    .addComponent(lblRetailerLocation))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblRetailerName)
                                .addGap(30, 30, 30)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProductName)
                            .addComponent(txtSellingPrice)
                            .addComponent(btnAddRetailer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spnQuantity, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnBackRetailer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRetailerName))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRetailerLocation)
                    .addComponent(txtSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPharmacyContact)
                    .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(btnAddRetailer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackRetailerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackRetailerActionPerformed
        // TODO add your handling code here:
        // Retrieve inputs from GUI components
        RequestJPanel retailerAdminJPanel = new RequestJPanel(AdminLayout, business,retailer, database );
        AdminLayout.add("RetailerAdminJPanel", retailerAdminJPanel);
        CardLayout layout = (CardLayout) AdminLayout.getLayout();
        layout.next(AdminLayout);
    }//GEN-LAST:event_btnBackRetailerActionPerformed

    private void btnAddRetailerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRetailerActionPerformed
        // TODO add your handling code here:
        // Retrieve inputs
        String productName = txtProductName.getText().trim();
        String sellingPriceText = txtSellingPrice.getText().trim();
        int quantity = (int) spnQuantity.getValue();

        if (productName.isEmpty() || sellingPriceText.isEmpty() || quantity <= 0) {
            JOptionPane.showMessageDialog(this, "All fields are mandatory, and quantity must be greater than 0.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double sellingPrice;
        try {
            sellingPrice = Double.parseDouble(sellingPriceText);
            if (sellingPrice <= 0) {
                JOptionPane.showMessageDialog(this, "Selling price must be greater than 0.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for selling price.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Create product document
            Document product = new Document("retailerId", retailer.getId().toString())
                    .append("productName", productName)
                    .append("sellingPrice", sellingPrice)
                    .append("quantity", quantity);

            // Insert product into collection
            retailerProductCollection.insertOne(product);

            JOptionPane.showMessageDialog(this, "Product added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Clear fields
            txtProductName.setText("");
            txtSellingPrice.setText("");
            spnQuantity.setValue(0);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error while adding product: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddRetailerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRetailer;
    private javax.swing.JButton btnBackRetailer;
    private javax.swing.JLabel lblPharmacyContact;
    private javax.swing.JLabel lblRetailerLocation;
    private javax.swing.JLabel lblRetailerName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JSpinner spnQuantity;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtSellingPrice;
    // End of variables declaration//GEN-END:variables
}
