/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Retailer;

import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import database.CRUDOperations;
import database.Connection;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Business.Business;
import model.Farmer.Farmer;
import model.Retailer.Retailer;
import org.bson.Document;
import org.bson.types.ObjectId;

/**
 *
 * @author Nilay
 */
public class RequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestJPanel
     */
    /**
     * Creates new form ProduceListJPanel
     */
    Business business;
    Retailer retailer;
//     Retailer retailer;
    MongoDatabase database;
    MongoCollection<Document> productCollection;
    MongoCollection<Document> requestCollection;
    CRUDOperations crud = new CRUDOperations();
    JPanel adminLayout;

    public RequestJPanel(JPanel cardSequencePanel, Business business, Retailer retailer, MongoDatabase prevdatabase) {
        initComponents();

        this.business = business;
        this.retailer = retailer;
        this.database = new Connection().connectToDatabase();
        this.productCollection = this.database.getCollection("RetailerProduct");
        this.requestCollection = this.database.getCollection("RetailerRequest");
        this.adminLayout = cardSequencePanel;
        this.database = database;
         populateProductTable();
        populateRequestedTable();
    }

     private void populateProductTable() {
        DefaultTableModel model = (DefaultTableModel) tblProductDetails.getModel();
        model.setRowCount(0);

        try {
            // Fetch products sold by this retailer
            FindIterable<Document> products = crud.getRecordsByKey("retailerId", retailer.getId().toString(), productCollection);

            for (Document product : products) {
                Object[] row = new Object[3];
                row[0] = product.getString("productName");
                row[1] = product.getDouble("sellingPrice");
                row[2] = product.getInteger("quantity");
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void populateRequestedTable() {
        DefaultTableModel model = (DefaultTableModel) tblRequestedProductDetails.getModel();
        model.setRowCount(0);

        try {
            // Fetch products requested by this retailer
            FindIterable<Document> requests = crud.getRecordsByKey("retailerId", retailer.getId().toString(), requestCollection);

            for (Document request : requests) {
                Object[] row = new Object[4];
                row[0] = request.getString("productName");
                row[1] = request.getDouble("requestedPrice");
                row[2] = request.getInteger("quantity");
                row[3] = request.getString("status");
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequestedProductDetails = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductDetails = new javax.swing.JTable();
        btnAddRetailer = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        tblRequestedProductDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product", "Required Price", "Quantity", "Status"
            }
        ));
        tblRequestedProductDetails.setToolTipText("");
        jScrollPane1.setViewportView(tblRequestedProductDetails);

        btnAdd.setBackground(new java.awt.Color(0, 153, 204));
        btnAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add Request");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblProductDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product", "selling price", "quantity"
            }
        ));
        jScrollPane2.setViewportView(tblProductDetails);

        btnAddRetailer.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnAddRetailer.setText("Add Product");
        btnAddRetailer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRetailerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddRetailer)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(362, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnAddRetailer)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdd)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) adminLayout.getLayout(); // 确保 adminLayout 是 JPanel
        AddRequestJPanel addRetailerJPanel = new AddRequestJPanel(adminLayout, database, business, retailer);
        adminLayout.add("AddRetailerJPanel", addRetailerJPanel);
        layout.next(adminLayout);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAddRetailerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRetailerActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) adminLayout.getLayout(); // 确保 adminLayout 是 JPanel
        AddProductJPanel addProductJPanel = new AddProductJPanel(adminLayout, database, business, retailer);
        adminLayout.add("AddRetailerJPanel", addProductJPanel);
        layout.next(adminLayout);
    }//GEN-LAST:event_btnAddRetailerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddRetailer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProductDetails;
    private javax.swing.JTable tblRequestedProductDetails;
    // End of variables declaration//GEN-END:variables
}
