/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.FoodProcessorUI;

import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import database.CRUDOperations;
import database.Connection;

import java.awt.CardLayout;
import javax.print.Doc;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import model.Business.Business;
import model.FoodProcessItem.FoodProcessItemDirectory;
import org.bson.Document;
import org.bson.types.ObjectId;
import ui.MainLoginJPanel;


public class RequestedItemsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form requestedItemsJPanel
     */
    JPanel cardSequencePanel;
    MongoDatabase database;
    FoodProcessItemDirectory medicalEquipmentSupplier;
    Business business;
    MongoCollection<Document> supplierCollection;
    MongoCollection<Document> equipmentCollection;
    MongoCollection<Document> supplierEquipmentCollection;
    MongoCollection<Document> requestEquipmentCollection;
    MongoCollection<Document> hospitalCollection;
    CRUDOperations crudOperations = new CRUDOperations();

    public RequestedItemsJPanel(JPanel cardSequencePanel, FoodProcessItemDirectory medicalEquipmentSupplier, MongoDatabase databases, Business business) {
        initComponents();
        this.cardSequencePanel = cardSequencePanel;
        this.medicalEquipmentSupplier = medicalEquipmentSupplier;
        this.database = new Connection().connectToDatabase();
        this.business = business;
        supplierCollection = database.getCollection("Supplier");
        equipmentCollection = database.getCollection("MedicalEquipment");
        supplierEquipmentCollection = database.getCollection("SupplierEquipment");
        requestEquipmentCollection = database.getCollection("RequestEquipment");
        hospitalCollection = database.getCollection("Hospital");

        populateRequestedItems();
    }

    private void populateRequestedItems() {
        DefaultTableModel model = (DefaultTableModel) tblRequestedItems.getModel();
        model.setRowCount(0); // Clear the existing table

//        find all the equipments that were requested for this supplier
        FindIterable<Document> requestEquipment = crudOperations.getRecordsByKey("supplierId", medicalEquipmentSupplier.getId().toString(), requestEquipmentCollection);
        for (Document document : requestEquipment) {
            String equipmentId = document.getString("equipmentId");
            String status = document.getString("status");
            System.out.println("equipmentId: " + equipmentId);
            System.out.println("status: " + status);
            Document equipment = crudOperations.getFirstRecordByKey("_id", new ObjectId(equipmentId), equipmentCollection);
            System.out.println("equipment: " + equipment);
            String equipmentName = equipment.getString("equipmentName");
            String equipmentPurpose = equipment.getString("equipmentPurpose");
            String hospitalId = document.getString("hospitalId");
            Document hospital = crudOperations.getFirstRecordByKey("_id", new ObjectId(hospitalId), hospitalCollection);
            String hospitalName = hospital.getString("hospitalName");
            String hospitalLocation = hospital.getString("hospitalLocation");
            Object[] row = {equipmentName, equipmentPurpose, hospitalName, hospitalLocation, status};
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequestedItems = new javax.swing.JTable();
        btnUpdateStatus = new javax.swing.JButton();
        lblMedicalEquipment1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 223, 164));

        tblRequestedItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item Name", "Receiver Name", "Quantity", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblRequestedItems);

        btnUpdateStatus.setBackground(new java.awt.Color(255, 102, 0));
        btnUpdateStatus.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnUpdateStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateStatus.setText("Update Status");
        btnUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStatusActionPerformed(evt);
            }
        });

        lblMedicalEquipment1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblMedicalEquipment1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedicalEquipment1.setText("REQUESTED EQUIPMENTS");
        lblMedicalEquipment1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedicalEquipment1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblMedicalEquipment1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnUpdateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStatusActionPerformed
        // TODO add your handling code here:
        String status = JOptionPane.showInputDialog("Enter the status of the equipment");
        int selectedRow = tblRequestedItems.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first to update the status", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String equipmentName = tblRequestedItems.getValueAt(selectedRow, 0).toString();
        Document equipment = crudOperations.getFirstRecordByKey("equipmentName", equipmentName, equipmentCollection);
        String equipmentId = equipment.getObjectId("_id").toString();
        String hospitalName = tblRequestedItems.getValueAt(selectedRow, 2).toString();
        Document hospital = crudOperations.getFirstRecordByKey("hospitalName", hospitalName, hospitalCollection);
        String hospitalId = hospital.getObjectId("_id").toString();
        Document requestEquipment = crudOperations.getRecordByTwoKeys("equipmentId", equipmentId, "hospitalId", hospitalId, requestEquipmentCollection);
        ObjectId requestId = requestEquipment.getObjectId("_id");
        crudOperations.updateStringById(requestId, "status", status, requestEquipmentCollection);
        populateRequestedItems();
    }//GEN-LAST:event_btnUpdateStatusActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMedicalEquipment1;
    private javax.swing.JTable tblRequestedItems;
    // End of variables declaration//GEN-END:variables
}
